version: "3.8"

services:
  # VertoCoin Core Node
  vertocoin-core:
    build:
      context: .
      dockerfile: Dockerfile
    image: vertocoin:latest
    container_name: vertocoin-core
    restart: always
    ports:
      # Main network ports
      - "9332:9332" # RPC port
      - "9333:9333" # P2P port
      # ZMQ notification ports
      # - "28332:28332" # Raw block notifications
      # - "28333:28333" # Raw transaction notifications
      # - "28334:28334" # Block hash notifications
      # - "28335:28335" # Transaction hash notifications
    volumes:
      # Persistent blockchain data
      - vertocoin-data:/home/vertocoin/.vertocoin
      # Tor-enabled configuration
      # - ./vertocoin-tor.conf:/home/vertocoin/.vertocoin/bitcoin.conf:ro
    networks:
      - vertocoin-network
    depends_on:
      - tor-proxy
      - tor
    healthcheck:
      test:
        [
          "CMD",
          "vertocoin-cli",
          "-conf=/home/vertocoin/.vertocoin/bitcoin.conf",
          "getblockchaininfo",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Tor proxy for enhanced privacy
  tor:
    image: goldy/tor-hidden-service:latest
    container_name: vertocoin-tor
    restart: always
    environment:
      # VertoCoin node hidden service
      - SERVICE1_TOR_SERVICE_HOSTS=80:vertocoin-core:9333
      - SERVICE1_TOR_SERVICE_VERSION=3
      # Optional: Set a custom private key (leave empty for auto-generation)
      # - SERVICE1_TOR_SERVICE_KEY=<your_private_key>
    volumes:
      - tor-data:/var/lib/tor
    networks:
      - vertocoin-network
    depends_on:
      - vertocoin-core

  # Tor SOCKS proxy for outbound connections
  tor-proxy:
    image: peterdavehello/tor-socks-proxy:latest
    container_name: vertocoin-tor-proxy
    restart: always
    ports:
      - "127.0.0.1:9050:9050" # SOCKS proxy port (bind to localhost only)
    networks:
      - vertocoin-network
    environment:
      - TOR_OPTS=--SocksPort 0.0.0.0:9050

  explorer:
    image: amirulmus/vertomax-explore:latest
    container_name: vertocoin-explorer
    restart: always
    ports:
      - "3002:3002"
    environment:
      - BTCEXP_HOST=0.0.0.0
      - BTCEXP_PORT=3002
      - BTCEXP_BITCOIND_HOST=vertocoin-node
      - BTCEXP_BITCOIND_PORT=9332
      - BTCEXP_BITCOIND_USER=vertomax
      - BTCEXP_BITCOIND_PASS=Vertomax2025
      - BTCEXP_DISPLAY_CURRENCY=vto
      - BTCEXP_LOCAL_CURRENCY=USD
      # - BTCEXP_COIN=VTO
      # - BTCEXP_ADDRESS_API=electrumx
      # - BTCEXP_ELECTRUMX_SERVERS=tcp://electrumx:50001
    networks:
      - vertocoin-network
    depends_on:
      - vertocoin-core

  # VertoCoin Core Node (Regtest for development)
  # vertocoin-regtest:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   image: vertocoin:latest
  #   container_name: vertocoin-regtest
  #   restart: always
  #   ports:
  #     - "19443:19443" # Regtest RPC port
  #     - "19444:19444" # Regtest P2P port
  #   volumes:
  #     - vertocoin-regtest-data:/home/vertocoin/.vertocoin
  #   environment:
  #     - VERTOCOIN_NETWORK=regtest
  #   networks:
  #     - vertocoin-network
  #   command:
  #     [
  #       "vertocoind",
  #       "-regtest",
  #       "-conf=/home/vertocoin/.vertocoin/vertocoin.conf",
  #     ]
  #   profiles:
  #     - regtest
  #   healthcheck:
  #     test:
  #       [
  #         "CMD",
  #         "vertocoin-cli",
  #         "-regtest",
  #         "-conf=/home/vertocoin/.vertocoin/vertocoin.conf",
  #         "getblockchaininfo",
  #       ]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 30s

  # Optional: Block Explorer (if you want to add one later)
  # vertocoin-explorer:
  #   image: nginx:alpine
  #   container_name: vertocoin-explorer
  #   restart: always
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ./explorer:/usr/share/nginx/html:ro
  #   networks:
  #     - vertocoin-network
  #   profiles:
  #     - explorer

  # Optional: Prometheus monitoring
  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: vertocoin-prometheus
  #   restart: always
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
  #     - prometheus-data:/prometheus
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'
  #     - '--storage.tsdb.path=/prometheus'
  #     - '--web.console.libraries=/etc/prometheus/console_libraries'
  #     - '--web.console.templates=/etc/prometheus/consoles'
  #   networks:
  #     - vertocoin-network
  #   profiles:
  #     - monitoring

volumes:
  # Persistent data volumes
  vertocoin-data:
    driver: local

  tor-data:
    driver: local

  # prometheus-data:
  #   driver: local

networks:
  vertocoin-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.50.0.0/16
